import "Graphics.dll" {
  g2d_BackColor(int)
  g2d_Box(int,int,int,int,int)
  g2d_Circle(int,int,int,int)
  g2d_DrawAlphaImage(int,int,int)
  g2d_DrawImage(int,int,int,int,int)
  g2d_DrawText(int,int,int,int,int)
  int g2d_GetBuffer()
  int g2d_GetBufferPitch()
  int g2d_GetBufferPixelFormat()
  g2d_SetFont(int)
  g2d_SetMode(int)
  g2d_Ellipse(int,int,int,int,int)
  g2d_FillArea(int,int,int,int)
  g2d_FrontColor(int)
  g2d_Line(int,int,int,int,int)
  g2d_LineXY(int,int,int,int,int)
  g2d_Plot(int,int,int)
  int g2d_GetColor(int,int)
  int g2d_StartDrawing(int)
  g2d_StopDrawing()
  int g2d_GetTextHeight(int)
  int g2d_GetTextWidth(int)
  ///////////////////
  int Image_Catch(int)
  int Image_CatchEx(int,int)
  int Image_Copy(int)
  int Image_Create(int,int,int)
  Image_Free(int)
  int Image_Grab(int,int,int,int,int)
  int Image_GetDepth(int)
  int Image_GetHeight(int)
  int Image_GetWidth(int)
  int Image_GetHandle(int)
  int Image_GetOutput(int)
  int Image_Exist(int)
  int Image_Load(int)
  int Image_LoadEx(int,int)
  Image_Resize(int,int,int)
  int Image_Save(int,int,int,int)
  ////////////////////////
  int Screen_GetAvailableMemory()
  Screen_SetGamma(int,int,int,int)
  Screen_Clear(int)
  Screen_Close()
  Screen_DisplayRGBFilter(int,int,int,int,int,int,int)
  int Screen_ExamineScreenModes()
  Screen_FlipBuffers(int)
  int Screen_IsActive()
  int Screen_NextScreenMode()
  int Screen_Create(int,int,int,int)
  int Screen_CreateWindowed(int,int,int,int,int,int,int,int)
  int Screen_GetHandle()
  int Screen_GetDepth()
  int Screen_GetHeight()
  int Screen_GetWidth()
  int Screen_GetRefreshRate()
  Screen_SetRefreshRate(int)
  int Screen_GetOutput()
  Screen_SetFrameRate(int)
  Screen_StartFX()
  Screen_StopFX()
  ////////////////////////
  int Sprite3D_Init()
  int Sprite3D_Create(int)
  Sprite3D_Display(int,int,int,int)
  Sprite3D_Free(int)
  int Sprite3D_Exist(int)
  Sprite3D_Rotate(int,int,int)
  Sprite3D_BlendingMode(int,int)
  Sprite3D_SetQuality(int)
  Sprite3D_Start3D()
  Sprite3D_Stop3D()
  Sprite3D_Transform(int,int,int,int,int,int,int,int,int,int,int,int,int)
  Sprite3D_Zoom(int,int,int)
  ///////////////////////////
  int Sprite2D_Init()
  int Sprite2D_Catch(int,int)
  Sprite2D_ChangeAlphaIntensity(int,int,int)
  int Sprite2D_Clip(int,int,int,int,int)
  int Sprite2D_Copy(int,int)
  int Sprite2D_Create(int,int,int)
  Sprite2D_DisplayAlpha(int,int,int)
  Sprite2D_DisplayShadow(int,int,int)
  Sprite2D_DisplaySolid(int,int,int,int)
  Sprite2D_Display(int,int,int)
  Sprite2D_DisplayTranslucent(int,int,int,int)
  Sprite2D_DisplayTransparent(int,int,int)
  Sprite2D_Free(int)
  int Sprite2D_Grab(int,int,int,int,int)
  int Sprite2D_Exist(int)
  int Sprite2D_Load(int,int)
  int Sprite2D_Collision(int,int,int,int,int,int)
  int Sprite2D_GetDepth(int)
  int Sprite2D_GetHeight(int)
  int Sprite2D_GetWidth(int)
  int Sprite2D_GetHandle(int)
  int Sprite2D_GetOutput(int)
  int Sprite2D_PixelCollision(int,int,int,int,int,int)
  Sprite2D_SetTransparentColor(int,int)
  Sprite2D_UseBuffer(int)
  ////////////////////////
  int Font_GetHandle(int)
  Font_Free(int)
  int Font_Exist(int)
  int Font_Load(int,int)
  int Font_LoadEx(int,int,int)
}
