/******************************************************************************
*
* Copyright (C) 2006, The Gentee Group. All rights reserved. 
* This file is part of the Gentee open source project <http://www.gentee.com>. 
* 
* THIS FILE IS PROVIDED UNDER THE TERMS OF THE GENTEE LICENSE ("AGREEMENT"). 
* ANY USE, REPRODUCTION OR DISTRIBUTION OF THIS FILE CONSTITUTES RECIPIENTS 
* ACCEPTANCE OF THE AGREEMENT.
*
* cmdlist_c 25.01.2008 0.0.A.
*
* Author: Generated with 'cmdlist' program 
* Contributors: SWR
*
* Summary: This file contains shift types of the embedded byte-code commands.
*
******************************************************************************/

#include <math.h>
#include "types.h"
#include "common.h"
#include "bytecode.h"

const ubyte embtypes[] = {
0x5, 0x3, 0x0, 0x1, 0x0, 0xB, 0x69, 0x6E, 
0x74, 0x0, 0x4, 0x5, 0x3, 0x0, 0x1, 0x0, 
0xC, 0x75, 0x69, 0x6E, 0x74, 0x0, 0x4, 0x5, 
0x3, 0x0, 0x1, 0x0, 0xC, 0x62, 0x79, 0x74, 
0x65, 0x0, 0x1, 0x5, 0x3, 0x0, 0x1, 0x0, 
0xD, 0x75, 0x62, 0x79, 0x74, 0x65, 0x0, 0x1, 
0x5, 0x3, 0x0, 0x1, 0x0, 0xD, 0x73, 0x68, 
0x6F, 0x72, 0x74, 0x0, 0x2, 0x5, 0x3, 0x0, 
0x1, 0x0, 0xE, 0x75, 0x73, 0x68, 0x6F, 0x72, 
0x74, 0x0, 0x2, 0x5, 0x3, 0x0, 0x1, 0x0, 
0xD, 0x66, 0x6C, 0x6F, 0x61, 0x74, 0x0, 0x4, 
0x5, 0x3, 0x0, 0x1, 0x0, 0xE, 0x64, 0x6F, 
0x75, 0x62, 0x6C, 0x65, 0x0, 0x8, 0x5, 0x3, 
0x0, 0x1, 0x0, 0xC, 0x6C, 0x6F, 0x6E, 0x67, 
0x0, 0x8, 0x5, 0x3, 0x0, 0x1, 0x0, 0xD, 
0x75, 0x6C, 0x6F, 0x6E, 0x67, 0x0, 0x8, 0x5, 
0x3, 0x2, 0x0, 0x0, 0x12, 0x72, 0x65, 0x73, 
0x65, 0x72, 0x76, 0x65, 0x64, 0x0, 0x4, 0x0, 
0x0, 0x5, 0x3, 0x2, 0x0, 0x0, 0x29, 0x62, 
0x75, 0x66, 0x0, 0x4, 0x0, 0x4, 0x2, 0x1, 
0x64, 0x61, 0x74, 0x61, 0x0, 0x2, 0x1, 0x75, 
0x73, 0x65, 0x0, 0x2, 0x1, 0x73, 0x69, 0x7A, 
0x65, 0x0, 0x2, 0x1, 0x73, 0x74, 0x65, 0x70, 
0x0, 0x0, 0x5, 0x3, 0x1, 0x0, 0x0, 0xE, 
0x73, 0x74, 0x72, 0x0, 0xC, 0x1, 0xC, 0x0, 
0x5, 0x3, 0x3, 0x0, 0x0, 0x28, 0x61, 0x72, 
0x72, 0x0, 0xC, 0x0, 0x0, 0x4, 0xC, 0x0, 
0x2, 0x1, 0x69, 0x74, 0x79, 0x70, 0x65, 0x0, 
0x2, 0x1, 0x69, 0x73, 0x69, 0x7A, 0x65, 0x0, 
0xB, 0x5, 0x64, 0x69, 0x6D, 0x0, 0x1, 0x20, 
0x5, 0x3, 0x3, 0x0, 0x0, 0x26, 0x63, 0x6F, 
0x6C, 0x6C, 0x65, 0x63, 0x74, 0x69, 0x6F, 0x6E, 
0x0, 0xC, 0x2, 0x0, 0x3, 0xC, 0x0, 0x2, 
0x1, 0x63, 0x6F, 0x75, 0x6E, 0x74, 0x0, 0x2, 
0x1, 0x66, 0x6C, 0x61, 0x67, 0x0, 0x5, 0x3, 
0x0, 0x1, 0x0, 0xB, 0x61, 0x6E, 0x79, 0x0, 
0x4, 0x5, 0x3, 0x0, 0x0, 0x0, 0x16, 0x66, 
0x6F, 0x72, 0x64, 0x61, 0x74, 0x61, 0x0, 0x1, 
0x2, 0x1, 0x69, 0x63, 0x75, 0x72, 0x0, 
};

const ubyte shifts[] = {
SH0_1, SH0_2, SH0_2, SH0_2, SHN1_2, SH0_2, SHN1_2, SH0_1, 
SH0_1, SH1_2, SH1_2, SH1_2, SH2_3, SH0_1, SH1_2, SH1_2, 
SH0_1, SHN1_1, SH0_1, SHN1_1, SH1_1, SH2_1, SH1_1, SHN1_1, 
SH0_1, SH0_1, SH0_1, SH0_1, SH0_1, SH1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SH0_1, SH0_1, SH0_1, SH0_1, SH0_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SH0_2, SH1_1, SHN1_1, SH1_2, SH0_2, SH0_2, SH0_1, SH0_1, 
SH0_1, SH0_1, SH0_1, SHN1_1, SHN2_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SH0_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SH0_1, SH1_1, 
SH0_1, SH1_1, SH1_1, SH0_1, SH1_1, SH0_1, SHN1_1, SHN1_1, 
SH1_1, SH0_1, SH1_1, SHN2_1, SHN2_1, SHN2_1, SHN2_1, SHN2_1, 
SHN2_1, SHN2_1, SHN2_1, SHN2_1, SHN2_1, SHN3_1, SHN3_1, SHN3_1, 
SH0_1, SH1_1, SH1_1, SH1_1, SH1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN2_1, 
SHN2_1, SHN2_1, SHN2_1, SHN2_1, SH0_1, SHN3_1, SHN3_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SH0_1, SHN1_1, SHN1_1, SHN1_1, SH0_1, SH0_1, SH0_1, SH0_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN2_1, SHN2_1, SHN2_1, SHN2_1, 
SH0_1, SHN3_1, SHN3_1, SHN3_1, SH1_1, SH1_1, SH1_1, SH1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SH0_1, SH0_1, SH0_1, SH0_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SH0_1, SH0_1, SH0_1, SH0_1, SHN1_1, SHN1_1, 
SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, SHN1_1, 
SH0_2, 
};


const ubyte embfuncs[] = {
'g', 'e', 't', 'i', 'd', 0, 0x83, TUint, TStr, TUint, TCollection, 
't', 'y', 'p', 'e', '_', 'h', 'a', 's', 'i', 'n', 'i', 't', 0, 0x81, TUint, TUint, 
't', 'y', 'p', 'e', '_', 'h', 'a', 's', 'd', 'e', 'l', 'e', 't', 'e', 0, 0x81, TUint, TUint, 
't', 'y', 'p', 'e', '_', 'i', 's', 'i', 'n', 'h', 'e', 'r', 'i', 't', 0, 0x82, TUint, TUint, TUint, 
't', 'y', 'p', 'e', '_', 'i', 'n', 'i', 't', 0, 0x82, TUint, TUint, TUint, 
't', 'y', 'p', 'e', '_', 'd', 'e', 'l', 'e', 't', 'e', 0, 0x2, TUint, TUint, 
's', 'i', 'z', 'e', 'o', 'f', 0, 0x81, TUint, TUint, 
'n', 'e', 'w', 0, 0x82, TUint, TUint, TUint, 
'd', 'e', 's', 't', 'r', 'o', 'y', 0, 0x1, TUint, 
'l', 'e', 'x', '_', 'i', 'n', 'i', 't', 0, 0x82, TUint, TUint, TUint, 
'l', 'e', 'x', '_', 'd', 'e', 'l', 'e', 't', 'e', 0, 0x1, TUint, 
'g', 'e', 'n', 't', 'e', 'e', '_', 'l', 'e', 'x', 0, 0x83, TUint, TUint, TUint, TUint, 
'g', 'e', 'n', 't', 'e', 'e', '_', 'c', 'o', 'm', 'p', 'i', 'l', 'e', 0, 0x81, TUint, TUint, 
'm', 'a', 'l', 'l', 'o', 'c', 0, 0x81, TUint, TUint, 
'm', 'c', 'o', 'p', 'y', 0, 0x83, TUint, TUint, TUint, TUint, 
'm', 'c', 'm', 'p', 0, 0x83, TInt, TUint, TUint, TUint, 
'm', 'f', 'r', 'e', 'e', 0, 0x1, TUint, 
'm', 'm', 'o', 'v', 'e', 0, 0x83, TUint, TUint, TUint, TUint, 
'm', 'z', 'e', 'r', 'o', 0, 0x82, TUint, TUint, TUint, 
'm', 'l', 'e', 'n', 0, 0x81, TUint, TUint, 
'm', 'l', 'e', 'n', 's', 'h', 0, 0x81, TUint, TUint, 
'g', 'e', 't', 'c', 'h', 0, 0x80, TUint, 
's', 'c', 'a', 'n', 0, 0x82, TUint, TUint, TUint, 
'r', 'e', 's', '_', 'g', 'e', 't', 's', 't', 'r', 0, 0x81, TStr, TUint, 
'c', 'r', 'c', 0, 0x83, TUint, TUint, TUint, TUint, 
's', 't', 'r', 'c', 'm', 'p', 0, 0x82, TInt, TUint, TUint, 
's', 't', 'r', 'c', 'm', 'p', 'i', 'g', 'n', 0, 0x82, TInt, TUint, TUint, 
's', 't', 'r', 'c', 'm', 'p', 'l', 'e', 'n', 0, 0x83, TInt, TUint, TUint, TUint, 
's', 't', 'r', 'c', 'm', 'p', 'i', 'g', 'n', 'l', 'e', 'n', 0, 0x83, TInt, TUint, TUint, TUint, 
'u', 's', 't', 'r', 'c', 'm', 'p', 'l', 'e', 'n', 0, 0x83, TInt, TUint, TUint, TUint, 
'u', 's', 't', 'r', 'c', 'm', 'p', 'i', 'g', 'n', 'l', 'e', 'n', 0, 0x83, TInt, TUint, TUint, TUint, 
'g', 'e', 'n', 't', 'e', 'e', '_', 'p', 't', 'r', 0, 0x81, TUint, TUint, 
'a', 'r', 'g', 'c', 0, 0x80, TUint, 
'a', 'r', 'g', 'v', 0, 0x82, TStr, TStr, TUint, 
'c', 'a', 'l', 'l', 'a', 'd', 'd', 'r', 0, 0x80, TUint, 
'q', 's', '_', 'i', 'n', 'i', 't', 0, 0x4, TUint, TUint, TUint, TUint, 
'q', 's', '_', 's', 'e', 'a', 'r', 'c', 'h', 0, 0x83, TUint, TUint, TUint, TUint, 
'f', 'a', 's', 't', 's', 'o', 'r', 't', 0, 0x4, TUint, TUint, TUint, TUint, 
's', 'o', 'r', 't', 0, 0x4, TUint, TUint, TUint, TUint, 
'g', 'e', 't', 't', 'e', 'm', 'p', 0, 0x80, TStr, 
'@', 'a', 'p', 'p', 'e', 'n', 'd', 0, 0x83, TBuf, TBuf, TUint, TUint, 
'@', 'i', 'n', 'i', 't', 0, 0x81, TBuf, TBuf, 
'@', 'd', 'e', 'l', 0, 0x83, TBuf, TBuf, TUint, TUint, 
'@', 'd', 'e', 'l', 'e', 't', 'e', 0, 0x1, TBuf, 
'@', 'c', 'l', 'e', 'a', 'r', 0, 0x81, TBuf, TBuf, 
'@', 'c', 'o', 'p', 'y', 0, 0x83, TBuf, TBuf, TUint, TUint, 
'@', 'i', 'n', 's', 'e', 'r', 't', 0, 0x84, TBuf, TBuf, TUint, TUint, TUint, 
'@', 'f', 'r', 'e', 'e', 0, 0x81, TBuf, TBuf, 
'@', 'p', 't', 'r', 0, 0x81, TUint, TBuf, 
'@', 'l', 'o', 'a', 'd', 0, 0x83, TBuf, TBuf, TUint, TUint, 
'@', 'a', 'r', 'r', 'a', 'y', 0, 0x82, TBuf, TBuf, TUint, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x82, TUint, TBuf, TUint, 
'@', 'r', 'e', 's', 'e', 'r', 'v', 'e', 0, 0x82, TBuf, TBuf, TUint, 
'@', 'e', 'x', 'p', 'a', 'n', 'd', 0, 0x82, TBuf, TBuf, TUint, 
'#', '*', 0, 0x81, TUint, TBuf, 
'#', '=', 0, 0x82, TBuf, TBuf, TBuf, 
'#', '+', '=', 0, 0x82, TBuf, TBuf, TBuf, 
'#', '+', '=', 0, 0x82, TBuf, TBuf, TUbyte, 
'#', '+', '=', 0, 0x82, TBuf, TBuf, TUshort, 
'#', '+', '=', 0, 0x82, TBuf, TBuf, TUint, 
'#', '+', '=', 0, 0x82, TBuf, TBuf, TUlong, 
'#', '=', '=', 0, 0x82, TUint, TBuf, TBuf, 
'@', 'f', 'i', 'n', 'd', 'c', 'h', 0, 0x83, TUint, TBuf, TUint, TUint, 
'@', 'f', 'i', 'n', 'd', 's', 'h', 0, 0x83, TUint, TBuf, TUint, TUint, 
'@', 'i', 'n', 'i', 't', 0, 0x81, TStr, TStr, 
'@', 'l', 'o', 'a', 'd', 0, 0x83, TStr, TStr, TUint, TUint, 
'@', 'c', 'o', 'p', 'y', 0, 0x82, TStr, TStr, TUint, 
'@', 'f', 'i', 'n', 'd', 'c', 'h', 0, 0x84, TUint, TStr, TUint, TUint, TUint, 
'@', 'f', 'i', 'n', 'd', 'c', 'h', 0, 0x82, TUint, TStr, TUint, 
'@', 'f', 'w', 'i', 'l', 'd', 'c', 'a', 'r', 'd', 0, 0x82, TUint, TStr, TStr, 
'@', 'p', 'r', 'i', 'n', 't', 0, 0x1, TStr, 
'p', 'r', 'i', 'n', 't', 0, 0x1, TStr, 
'@', 's', 'e', 't', 'l', 'e', 'n', 0, 0x82, TStr, TStr, TUint, 
'@', 's', 'u', 'b', 's', 't', 'r', 0, 0x84, TStr, TStr, TStr, TUint, TUint, 
'#', '=', 0, 0x82, TStr, TStr, TStr, 
'#', '+', '=', 0, 0x82, TStr, TStr, TStr, 
'#', '+', '=', 0, 0x82, TStr, TStr, TUint, 
'#', '*', 0, 0x81, TUint, TStr, 
'@', 'o', 'u', 't', '4', 0, 0x83, TStr, TStr, TStr, TUint, 
'@', 'o', 'u', 't', '8', 0, 0x83, TStr, TStr, TStr, TUlong, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x82, TUint, TReserved, TUint, 
'@', 'i', 'n', 'i', 't', 0, 0x81, TArr, TArr, 
'@', 'd', 'e', 'l', 'e', 't', 'e', 0, 0x1, TArr, 
'@', 'o', 'f', 't', 'y', 'p', 'e', 0, 0x2, TArr, TUint, 
'@', 'a', 'r', 'r', 'a', 'y', 0, 0x2, TArr, TUint, 
'@', 'a', 'r', 'r', 'a', 'y', 0, 0x3, TArr, TUint, TUint, 
'@', 'a', 'r', 'r', 'a', 'y', 0, 0x4, TArr, TUint, TUint, TUint, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x82, TUint, TArr, TUint, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x83, TUint, TArr, TUint, TUint, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x84, TUint, TArr, TUint, TUint, TUint, 
'#', '*', 0, 0x81, TUint, TArr, 
'@', 'e', 'x', 'p', 'a', 'n', 'd', 0, 0x82, TUint, TArr, TUint, 
'@', 'i', 'n', 's', 'e', 'r', 't', 0, 0x83, TUint, TArr, TUint, TUint, 
'@', 'd', 'e', 'l', 0, 0x83, TArr, TArr, TUint, TUint, 
'@', 'i', 'n', 'd', 'e', 'x', 0, 0x82, TUint, TCollection, TUint, 
'@', 'p', 't', 'r', 0, 0x82, TUint, TCollection, TUint, 
'@', 'g', 'e', 't', 't', 'y', 'p', 'e', 0, 0x82, TUint, TCollection, TUint, 
'#', '*', 0, 0x81, TUint, TCollection, 
's', 'i', 'n', 0, 0x81, TDouble, TDouble, 
'c', 'o', 's', 0, 0x81, TDouble, TDouble, 
't', 'a', 'n', 0, 0x81, TDouble, TDouble, 
'a', 's', 'i', 'n', 0, 0x81, TDouble, TDouble, 
'a', 'c', 'o', 's', 0, 0x81, TDouble, TDouble, 
'a', 't', 'a', 'n', 0, 0x81, TDouble, TDouble, 
'e', 'x', 'p', 0, 0x81, TDouble, TDouble, 
'l', 'n', 0, 0x81, TDouble, TDouble, 
'l', 'o', 'g', 0, 0x81, TDouble, TDouble, 
'p', 'o', 'w', 0, 0x82, TDouble, TDouble, TDouble, 
's', 'q', 'r', 't', 0, 0x81, TDouble, TDouble, 
'a', 'b', 's', 0, 0x81, TUint, TInt, 
'f', 'a', 'b', 's', 0, 0x81, TDouble, TDouble, 
'm', 'o', 'd', 'f', 0, 0x82, TDouble, TDouble, TUint, 
'c', 'e', 'i', 'l', 0, 0x81, TDouble, TDouble, 
'f', 'l', 'o', 'o', 'r', 0, 0x81, TDouble, TDouble, 
's', 't', 'r', 't', 'o', 'l', 0, 0x83, TInt, TUint, TUint, TUint, 
's', 't', 'r', 't', 'o', 'u', 'l', 0, 0x83, TUint, TUint, TUint, TUint, 
'a', 't', 'o', 'f', 0, 0x81, TDouble, TUint, 
'a', 't', 'o', 'i', '6', '4', 0, 0x81, TLong, TUint, 
};





const CmpInfo pCmpInfo[] ={
    {"CNone",        "Error command"},
    {"TInt",         "int type"},
    {"TUint",        "uint type"},
    {"TByte",        "byte type"},
    {"TUbyte",       "ubyte type"},
    {"TShort",       "short type"},
    {"TUshort",      "ushort type"},
    {"TFloat",       "float type"},
    {"TDouble",      "double type"},
    {"TLong",        "long type"},
    {"TUlong",       "ulong type"},
    {"TReserved",    "reserved type"},
    {"TBuf",         "buf type"},
    {"TStr",         "str type"},
    {"TArr",         "arr type"},
    {"TCollection",  "collection type"},
    {"TAny",         "any type"},
    {"TFordata",     "foreach type"},
    {"CNop",         "The command does nothing"},
    {"CGoto",        "The unconditional jump."},
    {"CGotonocls",   "The unconditional jump without clearing stack."},
    {"CIfze",        "The conditional jump"},
    {"CIfznocls",    "The conditional jump without clearing stack"},
    {"CIfnze",       "The conditional jump"},
    {"CIfnznocls",   "The conditional jump without clearing stack."},
    {"CByload",      "The next ubyte push into stack. GE only"},
    {"CShload",      "The next ushort push into stack. GE only"},
    {"CDwload",      "The next uint push into stack."},
    {"CCmdload",     "The next ID push into stack."},
    {"CResload",     "The next ID (resource) push into stack."},
    {"CQwload",      "The next ulong push into stack."},
    {"CDwsload",     "The next uints ( cmd 1 ) ( cmd 2 ) push into the stack"},
    {"CVarload",     "Load the value of parameter or variable with number ( cmd 1)"},
    {"CVarptrload",  "Load the pointer to value of parameter or variable with number ( cmd 1)"},
    {"CDatasize",    "Load the pointer to the next data and the size"},
    {"CLoglongtrue", "Return 1 if ulong in stack is not zero"},
    {"CLognot",      "Logical not"},
    {"CLoglongnot",  "Logical NOT for long ulong"},
    {"CDup",         "Duplicate top value"},
    {"CDuplong",     "Duplicate two top value"},
    {"CTop",         "Return the pointer to top"},
    {"CPop",         "Delete the top value"},
    {"CGetUB",       "* ( pubyte )"},
    {"CGetB",        "* ( pbyte )"},
    {"CGetUS",       "* ( pushort )"},
    {"CGetS",        "* ( pshort )"},
    {"CGetI",        "* ( puint && pint && float )"},
    {"CGetL",        "* ( pulong && plong && double )"},
    {"CSetUB",       "* ( pubyte ) ="},
    {"CSetB",        "* ( pbyte ) ="},
    {"CSetUS",       "* ( pushort ) ="},
    {"CSetS",        "* ( pshort ) ="},
    {"CSetI",        "* ( puint && pint && float ) ="},
    {"CSetL",        "* ( pulong && plong && double ) ="},
    {"CAddUIUI",     "+"},
    {"CSubUIUI",     "-"},
    {"CMulUIUI",     "*"},
    {"CDivUIUI",     "/"},
    {"CModUIUI",     "%"},
    {"CAndUIUI",     "&"},
    {"COrUIUI",      "|"},
    {"CXorUIUI",     "^"},
    {"CLeftUIUI",    "<<"},
    {"CRightUIUI",   ">>"},
    {"CLessUIUI",    "<"},
    {"CGreaterUIUI", ">"},
    {"CEqUIUI",      "=="},
    {"CNotUI",       "~"},
    {"CIncLeftUI",   "++i"},
    {"CIncRightUI",  "i++"},
    {"CDecLeftUI",   "--i"},
    {"CDecRightUI",  "i--"},
    {"CAddUI",       "+="},
    {"CSubUI",       "-="},
    {"CMulUI",       "*="},
    {"CDivUI",       "/="},
    {"CModUI",       "%="},
    {"CAndUI",       "&="},
    {"COrUI",        "|="},
    {"CXorUI",       "^="},
    {"CLeftUI",      "<<="},
    {"CRightUI",     ">>="},
    {"CVarsInit",    "Initialize variables in block cmd1 "},
    {"CGetText",     "Get current output of text function"},
    {"CSetText",     "Print string to current output of text function"},
    {"CPtrglobal",   "Get to the global variable"},
    {"CSubcall",     "Call a subfunc cmd 1 - goto"},
    {"CSubret",      "The number of returned uint cmd 1"},
    {"CSubpar",      "Paraneters of subfunc. cmd 1 - Set block cndshift = 1"},
    {"CSubreturn",   "Return from a subfunc"},
    {"CCmdcall",     "Call a funcion"},
    {"CCallstd",     "Call a stdcall or cdecl funcion"},
    {"CReturn",      "Return from the function."},
    {"CDbgTrace",    "Debug line tracing"},
    {"CDbgFunc",     "Debug func entering"},
    {"CMulII",       "*"},
    {"CDivII",       "/"},
    {"CModII",       "%"},
    {"CLeftII",      "<<"},
    {"CRightII",     ">>"},
    {"CSignI",       "change sign"},
    {"CLessII",      "<"},
    {"CGreaterII",   ">"},
    {"CMulI",        "*="},
    {"CDivI",        "/="},
    {"CModI",        "%="},
    {"CLeftI",       "<<="},
    {"CRightI",      ">>="},
    {"CMulB",        "*="},
    {"CDivB",        "/="},
    {"CModB",        "%="},
    {"CLeftB",       "<<="},
    {"CRightB",      ">>="},
    {"CMulS",        "*="},
    {"CDivS",        "/="},
    {"CModS",        "%="},
    {"CLeftS",       "<<="},
    {"CRightS",      ">>="},
    {"Cd2f",         "double 2 float"},
    {"Cd2i",         "double 2 int"},
    {"Cd2l",         "double 2 long"},
    {"Cf2d",         "float 2 double"},
    {"Cf2i",         "float 2 int"},
    {"Cf2l",         "float 2 long"},
    {"Ci2d",         "int 2 double"},
    {"Ci2f",         "int 2 float"},
    {"Ci2l",         "int 2 long"},
    {"Cl2d",         "long 2 double"},
    {"Cl2f",         "long 2 float"},
    {"Cl2i",         "long 2 int"},
    {"Cui2d",        "uint 2 double"},
    {"Cui2f",        "uint 2 float"},
    {"Cui2l",        "uint 2 long"},
    {"CAddULUL",     "+"},
    {"CSubULUL",     "-"},
    {"CMulULUL",     "*"},
    {"CDivULUL",     "/"},
    {"CModULUL",     "%"},
    {"CAndULUL",     "&"},
    {"COrULUL",      "|"},
    {"CXorULUL",     "^"},
    {"CLeftULUL",    "<<"},
    {"CRightULUL",   ">>"},
    {"CLessULUL",    "<"},
    {"CGreaterULUL", ">"},
    {"CEqULUL",      "=="},
    {"CNotUL",       "~"},
    {"CIncLeftUL",   "++"},
    {"CIncRightUL",  "++"},
    {"CDecLeftUL",   "--"},
    {"CDecRightUL",  "--"},
    {"CAddUL",       "+="},
    {"CSubUL",       "-="},
    {"CMulUL",       "*="},
    {"CDivUL",       "/="},
    {"CModUL",       "%"},
    {"CAndUL",       "&="},
    {"COrUL",        "|="},
    {"CXorUL",       "&="},
    {"CLeftUL",      "<<="},
    {"CRightUL",     ">>="},
    {"CMulLL",       "*"},
    {"CDivLL",       "/"},
    {"CModLL",       "%"},
    {"CLeftLL",      "<<="},
    {"CRightLL",     ">>="},
    {"CSignL",       "sign"},
    {"CLessLL",      "<"},
    {"CGreaterLL",   ">"},
    {"CMulL",        "*="},
    {"CDivL",        "/="},
    {"CModL",        "%="},
    {"CLeftL",       "<<="},
    {"CRightL",      ">>="},
    {"CAddFF",       "+"},
    {"CSubFF",       "-"},
    {"CMulFF",       "*"},
    {"CDivFF",       "/"},
    {"CSignF",       "sign"},
    {"CLessFF",      "<"},
    {"CGreaterFF",   ">"},
    {"CEqFF",        "=="},
    {"CIncLeftF",    "++"},
    {"CIncRightF",   "++"},
    {"CDecLeftF",    "--"},
    {"CDecRightF",   "--"},
    {"CAddF",        "+="},
    {"CSubF",        "-="},
    {"CMulF",        "*="},
    {"CDivF",        "/="},
    {"CAddDD",       "+"},
    {"CSubDD",       "-"},
    {"CMulDD",       "*"},
    {"CDivDD",       "/"},
    {"CSignD",       "sign"},
    {"CLessDD",      "<"},
    {"CGreaterDD",   ">"},
    {"CEqDD",        "=="},
    {"CIncLeftD",    "++"},
    {"CIncRightD",   "++"},
    {"CDecLeftD",    "--"},
    {"CDecRightD",   "--"},
    {"CAddD",        "+="},
    {"CSubD",        "-="},
    {"CMulD",        "*="},
    {"CDivD",        "/="},
    {"CIncLeftUB",   "++"},
    {"CIncRightUB",  "++"},
    {"CDecLeftUB",   "--"},
    {"CDecRightUB",  "--"},
    {"CAddUB",       "+="},
    {"CSubUB",       "-="},
    {"CMulUB",       "*="},
    {"CDivUB",       "/="},
    {"CModUB",       "%="},
    {"CAndUB",       "&="},
    {"COrUB",        "|="},
    {"CXorUB",       "^="},
    {"CLeftUB",      "<<="},
    {"CRightUB",     ">>="},
    {"CIncLeftUS",   "++"},
    {"CIncRightUS",  "++"},
    {"CDecLeftUS",   "--"},
    {"CDecRightUS",  "--"},
    {"CAddUS",       "+="},
    {"CSubUS",       "-="},
    {"CMulUS",       "*="},
    {"CDivUS",       "/="},
    {"CModUS",       "%="},
    {"CAndUS",       "&="},
    {"COrUS",        "|="},
    {"CXorUS",       "^="},
    {"CLeftUS",      "<<="},
    {"CRightUS",     ">>="},
    {"CCollectadd",  "Run-time loading collection"},
};